/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
 * Generated on: 30-Jun-2025 15:55:43
 */

/*
 * 离散时间 IIR 滤波器(实数)
 * ----------------
 * 滤波器结构  : 直接 II 型，二阶节
 * 节数     : 4
 * 稳定     : 是
 * 线性相位   : 否
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * D:\matlab\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */


#define MWSPT_NSEC 5 
const float NUM[MWSPT_NSEC][3] = {
  {
   0.004975691438,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
   0.004632311873,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const float DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   -1.875265718,   0.8951684237 
  },
  {
                1,              0,              0 
  },
  {
                1,   -1.745850801,   0.7643800378 
  },
  {
                1,              0,              0 
  }
};
